import './globals.css';
import Nav from './auth/Nav';
import QueryWrapper from './auth/QueryWrapper';
import Provider from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className=' bg-slate-700'>

        <Provider>
          <QueryWrapper>
          <Nav/>
        {children}
        </QueryWrapper>
        </Provider>
        </body>
    </html>
  )
}
